### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tm31420** [GoldSaintEagle/ECDSA-SM2-Signing-Attack#1]
is there any way to use this attack without using a private key in the calculation?

I was studying this code today, and wanted your input on that idea.....

**Comment by tm31420** [comment]
hello?

**Comment by tm31420** [comment]
my email is tm31420@gmail.com , please respond.

**Comment by GoldSaintEagle** [comment]
sorry, I just noticed this issue today...
please note these attacks are not practical for real-world ecdsa applications.
I listed these issues just to show we need to be careful when using ecdsa.

**Comment by tm31420** [comment]
thanks for your response.
